# $Id: Makefile,v 10.106 2008/01/12 13:42:40 bostic Exp $

COMMON=	api_core.html \
	env_class.html \
	env_close.html \
	env_dbremove.html \
	env_dbrename.html \
	env_err.html \
	env_event_notify.html \
	env_failchk.html \
	env_fileid_reset.html \
	env_list.html \
	env_lsn_reset.html \
	env_open.html \
	env_remove.html \
	env_set_app_dispatch.html \
	env_set_cachesize.html \
	env_set_data_dir.html \
	env_set_encrypt.html \
	env_set_errcall.html \
	env_set_errpfx.html \
	env_set_feedback.html \
	env_set_flags.html \
	env_set_isalive.html \
	env_set_msgcall.html \
	env_set_rpc_server.html \
	env_set_intermediate_dir_mode.html \
	env_set_shm_key.html \
	env_set_thread_count.html \
	env_set_thread_id.html \
	env_set_thread_id_string.html \
	env_set_timeout.html \
	env_set_tmp_dir.html \
	env_set_verbose.html \
	env_strerror.html \
	env_version.html

C=	env_set_alloc.html \
	env_set_errfile.html \
	env_set_msgfile.html \
	env_stat.html

CXX=	env_set_alloc.html \
	env_set_errfile.html \
	env_set_error_stream.html \
	env_set_msg_stream.html \
	env_set_msgfile.html \
	env_stat.html
