# $Id: Makefile,v 1.11 2003/09/04 14:03:12 bostic Exp $

BUILD=  cksum.html client.html del.html disk.html intro.html java.html \
	lockng.html nosync.html priority.html queue.html repinit.html \
	tcl.html toc.html verify.html

all: ${BUILD}
