# $Id: Makefile,v 1.15 2002/06/22 14:01:11 bostic Exp $

BUILD=  asr.html cxx.html deadlock.html disk.html env.html intro.html \
	java.html lock.html lock_id_free.html log.html mp.html rpc.html \
	set_lk_max.html toc.html txn.html

all: ${BUILD}
