/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sleepycat_db_DbMpoolFile */

#ifndef _Included_com_sleepycat_db_DbMpoolFile
#define _Included_com_sleepycat_db_DbMpoolFile
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_sleepycat_db_DbMpoolFile
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_sleepycat_db_DbMpoolFile_close
  (JNIEnv *, jobject);

/*
 * Class:     com_sleepycat_db_DbMpoolFile
 * Method:    sync
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_sleepycat_db_DbMpoolFile_sync
  (JNIEnv *, jobject);

/*
 * Class:     com_sleepycat_db_DbMpoolFile
 * Method:    open
 * Signature: (Lcom/sleepycat/db/DbMpool;Ljava/lang/String;IIIJILcom/sleepycat/db/Dbt;[B)Lcom/sleepycat/db/DbMpoolFile;
 */
JNIEXPORT jobject JNICALL Java_com_sleepycat_db_DbMpoolFile_open
  (JNIEnv *, jclass, jobject, jstring, jint, jint, jint, jlong, jint, jobject, jbyteArray);

/*
 * Class:     com_sleepycat_db_DbMpoolFile
 * Method:    finalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_sleepycat_db_DbMpoolFile_finalize
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
