/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sleepycat_db_Db */

#ifndef _Included_com_sleepycat_db_Db
#define _Included_com_sleepycat_db_Db
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_sleepycat_db_Db
 * Method:    close
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_sleepycat_db_Db_close
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_sleepycat_db_Db
 * Method:    cursor
 * Signature: (Lcom/sleepycat/db/DbTxn;)Lcom/sleepycat/db/Dbc;
 */
JNIEXPORT jobject JNICALL Java_com_sleepycat_db_Db_cursor
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_sleepycat_db_Db
 * Method:    del
 * Signature: (Lcom/sleepycat/db/DbTxn;Lcom/sleepycat/db/Dbt;I)V
 */
JNIEXPORT void JNICALL Java_com_sleepycat_db_Db_del
  (JNIEnv *, jobject, jobject, jobject, jint);

/*
 * Class:     com_sleepycat_db_Db
 * Method:    fd
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_sleepycat_db_Db_fd
  (JNIEnv *, jobject);

/*
 * Class:     com_sleepycat_db_Db
 * Method:    get
 * Signature: (Lcom/sleepycat/db/DbTxn;Lcom/sleepycat/db/Dbt;Lcom/sleepycat/db/Dbt;I)V
 */
JNIEXPORT void JNICALL Java_com_sleepycat_db_Db_get
  (JNIEnv *, jobject, jobject, jobject, jobject, jint);

/*
 * Class:     com_sleepycat_db_Db
 * Method:    put
 * Signature: (Lcom/sleepycat/db/DbTxn;Lcom/sleepycat/db/Dbt;Lcom/sleepycat/db/Dbt;I)I
 */
JNIEXPORT jint JNICALL Java_com_sleepycat_db_Db_put
  (JNIEnv *, jobject, jobject, jobject, jobject, jint);

/*
 * Class:     com_sleepycat_db_Db
 * Method:    stat
 * Signature: (I)Lcom/sleepycat/db/DbBtreeStat;
 */
JNIEXPORT jobject JNICALL Java_com_sleepycat_db_Db_stat
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_sleepycat_db_Db
 * Method:    sync
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_sleepycat_db_Db_sync
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_sleepycat_db_Db
 * Method:    get_type
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_sleepycat_db_Db_get_1type
  (JNIEnv *, jobject);

/*
 * Class:     com_sleepycat_db_Db
 * Method:    open
 * Signature: (Ljava/lang/String;IIILcom/sleepycat/db/DbEnv;Lcom/sleepycat/db/DbInfo;)Lcom/sleepycat/db/Db;
 */
JNIEXPORT jobject JNICALL Java_com_sleepycat_db_Db_open
  (JNIEnv *, jclass, jstring, jint, jint, jint, jobject, jobject);

/*
 * Class:     com_sleepycat_db_Db
 * Method:    finalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_sleepycat_db_Db_finalize
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
