# $Id: Makefile,v 1.11 2006/09/13 16:43:03 bostic Exp $

BUILD=	alive.html \
	applog.html \
	collect.html \
	config.html \
	deprecate.html \
	disk.html \
	elect.html \
	intro.html \
	memp.html \
	pagesize.html \
	paniccall.html \
	rep_event.html \
	rep_set.html \
	source.html \
	toc.html

all: ${BUILD}
