# $Id: Makefile,v 1.11 2004/09/28 14:13:09 bostic Exp $

BUILD=  cput.html disk.html enomem.html err.html fileopen.html intro.html \
	java.html log.html repl.html rtc.html stat.html toc.html verb.html

all: ${BUILD}
