# $Id: Makefile,v 1.7 2007/05/04 12:37:15 bostic Exp $

BUILD=	cursor.html \
	disk.html \
	event.html \
	full_election.html \
	intro.html \
	memp_fput.html \
	memp_fset.html \
	toc.html \
	verb.html \
	verbose.html \
	win.html

all: ${BUILD}
