# $Id: Makefile,v 11.14 2004/11/03 16:38:07 bostic Exp $

BUILD= 	api_tcl.html db_close.html db_count.html db_cursor.html \
	db_del.html db_get.html db_get_join.html db_get_type.html \
	db_is_byteswapped.html db_join.html db_open.html db_put.html \
	db_remove.html db_rename.html db_stat.html db_sync.html \
	db_truncate.html dbc_close.html dbc_del.html dbc_dup.html \
	dbc_get.html dbc_put.html env_close.html env_dbremove.html \
	env_dbrename.html env_open.html env_remove.html txn.html \
	txn_abort.html txn_checkpoint.html txn_commit.html version.html

all: ${BUILD}
