# $Id: Makefile,v 11.5 2002/06/22 13:55:53 bostic Exp $

BUILD=  bt_compare.html bt_minkey.html bt_prefix.html bt_recnum.html \
	byteorder.html cachesize.html dup.html extentsize.html \
	h_ffactor.html h_hash.html h_nelem.html intro.html logrec.html \
	malloc.html pagesize.html re_source.html recno.html \
	renumber.html select.html

all: ${BUILD}
