# $Id: Makefile,v 1.11 2002/08/26 23:05:28 mjc Exp $

BUILD=	app_dispatch.html checkpoint.html cxx.html disk.html excl.html \
	fop.html hash_nelem.html incomplete.html intro.html java.html \
	log_register.html log_stat.html memp_sync.html toc.html

all: ${BUILD}
