# See the file LICENSE for redistribution information.
#
# Copyright (c) 2026 berkeleydb/libdb contributors.  All rights reserved.
#
# $Id$
#
# TEST	logverify001
# TEST	Log verification of a healthy, multi-file transactional log.
# TEST
# TEST	Drives the db_log_verify utility (DB_ENV->log_verify) over a log
# TEST	generated by a mixed workload -- btree, hash and recno access
# TEST	methods, sub-databases, committed and aborted transactions, and
# TEST	periodic checkpoints -- forced across a dozen physical log files by
# TEST	a small log_max.  This exercises the happy-path verification code in
# TEST	src/log/log_verify*.c: the LSN-chain walk, the per-txn structure
# TEST	checks, and the many log-record-type handlers in log_verify_auto.c.
# TEST	The verifier must report SUCCESS.
proc logverify001 { } {
	source ./include.tcl

	puts "Logverify001: Verify a healthy multi-file transactional log"

	env_cleanup $testdir

	# Small log_max so a modest workload rolls over many physical log
	# files (log verification is most interesting across file boundaries).
	set e [berkdb_env -create -home $testdir -txn -lock -log -log_max 65536]
	error_check_good env_open [is_valid_env $e] TRUE

	puts "\tLogverify001.a: Mixed-method transactional workload"

	# One database per access method, plus a sub-database file, so several
	# distinct log record types are emitted and later verified.
	set dbb [berkdb open -create -auto_commit -env $e -btree btree.db]
	error_check_good dbb_open [is_valid_db $dbb] TRUE
	set dbh [berkdb open -create -auto_commit -env $e -hash hash.db]
	error_check_good dbh_open [is_valid_db $dbh] TRUE
	set dbr [berkdb open -create -auto_commit -env $e -recno recno.db]
	error_check_good dbr_open [is_valid_db $dbr] TRUE
	set dbs1 [berkdb open -create -auto_commit -env $e -btree sub.db s1]
	error_check_good dbs1_open [is_valid_db $dbs1] TRUE
	set dbs2 [berkdb open -create -auto_commit -env $e -btree sub.db s2]
	error_check_good dbs2_open [is_valid_db $dbs2] TRUE

	set val [string repeat "logverify-payload-" 3]

	# Committed transactions across all methods.
	for { set i 0 } { $i < 1500 } { incr i } {
		set t [$e txn]
		error_check_good t_begin [is_valid_txn $t $e] TRUE
		error_check_good b_put [$dbb put -txn $t key$i $val$i] 0
		error_check_good h_put [$dbh put -txn $t key$i $val$i] 0
		error_check_good r_put [$dbr put -txn $t -append $val$i] \
		    [expr {$i + 1}]
		error_check_good s1_put [$dbs1 put -txn $t key$i $val$i] 0
		error_check_good s2_put [$dbs2 put -txn $t key$i $val$i] 0
		error_check_good t_commit [$t commit] 0
		if { $i % 150 == 0 } {
			error_check_good ckp [$e txn_checkpoint] 0
		}
	}

	puts "\tLogverify001.b: Aborted transactions (undo records)"
	for { set i 0 } { $i < 200 } { incr i } {
		set t [$e txn]
		error_check_good t_begin [is_valid_txn $t $e] TRUE
		error_check_good b_put [$dbb put -txn $t abkey$i $val] 0
		error_check_good h_put [$dbh put -txn $t abkey$i $val] 0
		error_check_good t_abort [$t abort] 0
	}

	# A few deletes for delete/replace record variety.
	set t [$e txn]
	for { set i 0 } { $i < 50 } { incr i } {
		error_check_good b_del [$dbb del -txn $t key$i] 0
	}
	error_check_good t_commit [$t commit] 0

	error_check_good ckp [$e txn_checkpoint] 0

	error_check_good dbs2_close [$dbs2 close] 0
	error_check_good dbs1_close [$dbs1 close] 0
	error_check_good dbr_close [$dbr close] 0
	error_check_good dbh_close [$dbh close] 0
	error_check_good dbb_close [$dbb close] 0
	error_check_good env_close [$e close] 0

	# Confirm the workload actually spanned several physical log files;
	# a single-file log would leave the cross-file paths uncovered.
	set logs [glob -nocomplain $testdir/log.*]
	error_check_good multiple_logfiles [expr {[llength $logs] > 3}] 1

	puts "\tLogverify001.c: db_log_verify must report SUCCESS"
	# verify_log (testutils.tcl) runs db_log_verify -h $testdir and checks
	# for the "Log verification ended and SUCCEEDED" message.  Returns 0
	# on success, 1 on failure.
	error_check_good log_verify_ok [verify_log $testdir] 0
}
