# $Id: Makefile,v 1.10 2002/06/22 14:01:10 bostic Exp $

BUILD=	alloc.html bigfile.html conflict.html disk.html getswap.html \
	gettype.html intro.html memp_fget.html rpc.html shared.html \
	toc.html txn_prepare.html

all: ${BUILD}
