# $Id: Makefile,v 10.9 2002/06/22 13:59:59 bostic Exp $

BUILD=  am_conv.html cam_conv.html config.html dead.html deaddbg.html \
	intro.html max.html nondb.html notxn.html page.html stdmode.html \
	timeout.html twopl.html

all: ${BUILD}
