# $Id: Makefile,v 10.11 2002/09/03 20:09:29 bostic Exp $

BUILD=  create.html db_config.html encrypt.html error.html faq.html \
	intro.html naming.html open.html region.html remote.html \
	security.html

all: ${BUILD}
