# $Id: Makefile,v 1.12 2007/07/06 23:08:01 mjc Exp $

COMMON=	env_set_cache_max.html \
	env_set_mp_mmapsize.html \
	memp_fclose.html \
	memp_fcreate.html \
	memp_fget.html \
	memp_fopen.html \
	memp_fput.html \
	memp_fsync.html \
	memp_list.html \
	memp_maxwrite.html \
	memp_openfd.html \
	memp_register.html \
	memp_set_clear_len.html \
	memp_set_fileid.html \
	memp_set_flags.html \
	memp_set_ftype.html \
	memp_set_lsn_offset.html \
	memp_set_maxsize.html \
	memp_set_pgcookie.html \
	memp_set_priority.html \
	memp_stat.html \
	memp_sync.html \
	memp_trickle.html \
	mempfile_class.html

CXX=	memp_class.html
