# $Id: Makefile,v 10.16 2004/10/18 20:10:41 bostic Exp $

BUILD=  aix.html conf.html flags.html freebsd.html hpux.html install.html \
	intro.html irix.html linux.html macosx.html notes.html osf1.html \
	qnx.html sco.html shlib.html small.html solaris.html sunos.html \
	test.html ultrix.html

all: ${BUILD}
