C=	set_func_close.html \
	set_func_dirfree.html \
	set_func_dirlist.html \
	set_func_exists.html \
	set_func_free.html \
	set_func_fsync.html \
	set_func_ftruncate.html \
	set_func_ioinfo.html \
	set_func_malloc.html \
	set_func_map.html \
	set_func_open.html \
	set_func_pread.html \
	set_func_pwrite.html \
	set_func_read.html \
	set_func_realloc.html \
	set_func_rename.html \
	set_func_seek.html \
	set_func_sleep.html \
	set_func_unlink.html \
	set_func_unmap.html \
	set_func_write.html \
	set_func_yield.html
