# $Id: Makefile,v 1.12 2002/06/22 14:01:09 bostic Exp $

BUILD=  callback.html db_dump.html disk.html handle.html incomplete.html \
	intro.html mutexlock.html notfound.html renumber.html \
	set_flags.html toc.html tx_recover.html

all: ${BUILD}
