# $Id: Makefile,v 11.12 2002/06/22 14:01:06 bostic Exp $

BUILD=  close.html cxx.html db.html db_cxx.html dbenv.html dbenv_cxx.html \
	dbinfo.html disk.html eacces.html eagain.html envopen.html \
	func.html intro.html java.html join.html jump_set.html \
	lock_detect.html lock_notheld.html lock_put.html lock_stat.html \
	log_register.html log_stat.html memp_stat.html open.html \
	rmw.html stat.html toc.html txn_begin.html txn_commit.html \
	txn_stat.html value_set.html xa.html

all: ${BUILD}
