# $Id: Makefile,v 1.5 2007/05/17 18:17:18 bostic Exp $

COMMON=	seq_class.html \
	seq_close.html \
	seq_get.html \
	seq_initial_value.html \
	seq_list.html \
	seq_open.html \
	seq_remove.html	\
	seq_set_cachesize.html \
	seq_set_flags.html \
	seq_set_range.html \
	seq_stat.html

C=
CXX=
