# $Id: Makefile,v 1.10 2006/07/18 02:06:13 alanb Exp $

BUILD=  app.html base_meth.html bulk.html comm.html elect.html ex.html \
	ex_comm.html ex_rq.html faq.html id.html init.html intro.html \
	mastersync.html mgr_meth.html newsite.html partition.html pri.html \
	trans.html

all: ${BUILD}
