# $Id: Makefile,v 1.12 2007/10/03 17:48:44 sue Exp $

BUILD=  app.html base_meth.html bulk.html clock_skew.html comm.html \
	elect.html ex.html ex_comm.html ex_rq.html faq.html id.html \
	init.html intro.html lease.html mastersync.html mgr_meth.html \
	newsite.html partition.html pri.html trans.html

all: ${BUILD}
