# $Id: Makefile,v 1.6 2005/11/08 02:45:17 bostic Exp $

BUILD=	autocommit.html \
	clear.html \
	disk.html \
	intro.html \
	isolation.html \
	joinenv.html \
	lockstat.html \
	mutex.html \
	toc.html

all: ${BUILD}
