# $Id: Makefile,v 10.7 2002/06/22 13:56:13 bostic Exp $

BUILD=	align.html dbsizes.html diskspace.html error.html faq.html \
	get_bulk.html partial.html perm.html stability.html struct.html \
	tune.html

all: ${BUILD}
