# $Id: Makefile,v 1.17 2007/07/12 18:27:42 bostic Exp $

COMMON=	db_associate.html \
	db_class.html \
	db_close.html \
	db_compact.html \
	db_cursor.html \
	db_del.html \
	db_err.html \
	db_exists.html \
	db_get.html \
	db_get_byteswapped.html \
	db_get_mpf.html \
	db_get_type.html \
	db_getenv.html \
	db_join.html \
	db_key_range.html \
	db_list.html \
	db_open.html \
	db_put.html \
	db_remove.html \
	db_rename.html \
	db_set_append_recno.html \
	db_set_bt_compare.html \
	db_set_bt_minkey.html \
	db_set_bt_prefix.html \
	db_set_cachesize.html \
	db_set_dup_compare.html \
	db_set_encrypt.html \
	db_set_errcall.html \
	db_set_errpfx.html \
	db_set_feedback.html \
	db_set_flags.html \
	db_set_h_compare.html \
	db_set_h_ffactor.html \
	db_set_h_hash.html \
	db_set_h_nelem.html \
	db_set_lorder.html \
	db_set_msgcall.html \
	db_set_pagesize.html \
	db_set_priority.html \
	db_set_q_extentsize.html \
	db_set_re_delim.html \
	db_set_re_len.html \
	db_set_re_pad.html \
	db_set_re_source.html \
	db_stat.html \
	db_sync.html \
	db_truncate.html \
	db_upgrade.html \
	db_verify.html \
	dbt_class.html

C=	db_fd.html \
	db_set_alloc.html \
	db_set_errfile.html \
	db_set_msgfile.html \
	dbt_bulk.html

CXX=	db_fd.html \
	db_set_alloc.html \
	db_set_errfile.html \
	db_set_error_stream.html \
	db_set_msg_stream.html \
	db_set_msgfile.html \
	dbt_bulk_class.html
