# $Id: Makefile,v 10.31 2004/09/15 19:40:07 bostic Exp $

BUILD=  close.html count.html curclose.html curdel.html curdup.html \
	curget.html curput.html cursor.html delete.html get.html \
	join.html open.html opensub.html ops.html put.html second.html \
	stat.html sync.html truncate.html upgrade.html verify.html
COPY=	second.javas

all: ${BUILD}
