# $Id: Makefile,v 10.29 2002/09/26 01:38:32 bostic Exp $

COPY=	solaris.txt
BUILD=  appsignals.html cache.html compatible.html copy.html \
	environ.html errorret.html faq.html mt.html namespace.html \
	ram.html runtime.html scope.html

all: ${BUILD}
